title: SydEthereum Meetup
description: >
  Monthly meetup in Sydney to learn about Ethereum technologies and usage.
theme: jekyll-theme-slate
twitter_username: SydEthereum
github_username: SydEthereum